#ifndef REQUESTTYPE_H
#define REQUESTTYPE_H

enum class RequestType {
    LOGIN_REQUEST = 1,
    DISPLAY_MENU_REQUEST,
    VIEW_SPECIFIC_DATE_MENU_REQUEST,
    ADD_EMPLOYEE_REQUEST
};

#endif // REQUESTTYPE_H
