#ifndef REQUESTTYPE_H
#define REQUESTTYPE_H

enum class RequestType {
    LOGIN_REQUEST = 1,
    DISPLAY_MENU_REQUEST,
    VIEW_SPECIFIC_DATE_MENU_REQUEST,
    ADD_EMPLOYEE_REQUEST,
    REMOVE_EMPLOYEE_REQUEST,
    ADD_MENU_ITEM_REQUEST,
    REMOVE_MENU_ITEM_REQUEST,
    GENERATE_REPORT_REQUEST,
    GET_RECOMMENDATION,
    ROLLOUT_NEXT_DAY_MENU,
    GET_NEXT_DAY_MENU_REQUEST
};

#endif // REQUESTTYPE_H
