#ifndef RESPONSETYPE_H
#define RESPONSETYPE_H

enum class ResponseType {
    SUCCESSFUL_LOGIN = 1,
    FAILED_LOGIN,
    DISPLAY_MENU,
    VIEW_SPECIFIC_DATE_MENU,
    FAILED_ADD_EMPLOYEE,
    SUCCESSFUL_ADD_EMPLOYEE,
    FAILED_REMOVE_EMPLOYEE,
    SUCCESSFUL_REMOVE_EMPLOYEE,
    ADD_MENU_ITEM,
    REMOVE_MENU_ITEM
};

#endif // RESPONSETYPE_H
