#ifndef RESPONSETYPE_H
#define RESPONSETYPE_H

enum class ResponseType {
    SERVER_RESPONSE,
    SUCCESSFUL_LOGIN,
    FAILED_LOGIN,
    DISPLAY_MENU,
    VIEW_SPECIFIC_DATE_MENU,
    FAILED_ADD_EMPLOYEE,
    SUCCESSFUL_ADD_EMPLOYEE,
    FAILED_REMOVE_EMPLOYEE,
    SUCCESSFUL_REMOVE_EMPLOYEE,
    ADD_MENU_ITEM,
    REMOVE_MENU_ITEM,
    GENERATE_REPORT,
    GET_RECOMMENDATION,
    ROLLOUT_NEXT_DAY_MENU,
    DISPLAY_NEXT_DAY_MENU
};

#endif // RESPONSETYPE_H
